name: iOS Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ develop ]
    
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    if: github.event.pull_request.draft == false
    runs-on: macos-14

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0
          
      - name: Run Linter
        run: |
          swiftlint --strict

      - name: Xcode select
        run: |
          sudo xcode-select -s /Applications/Xcode_15.3.app
          
      - name: Build and Test
        run: |
          xcodebuild -workspace "Homepage-DemoApp.xcworkspace" -scheme Homepage-DemoApp test \
           -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
           -enableCodeCoverage YES -resultBundlePath result.xcresult
           