name: iOS Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ develop ]
    
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0
          
      - name: Run Linter
        if: github.event.pull_request.draft == false
        run: |
          brew install swiftlint
          swiftlint --strict

      - name: Xcode select
        run: |
          sudo xcode-select -s /Applications/Xcode_15.3.app
          
      - name: Build and Test
        run: |
          xcodebuild -workspace "Homepage.xcworkspace" -scheme Homepage-DemoApp test \
           -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
           -enableCodeCoverage YES \
           -resultBundlePath result.xcresult
      
      - name: Run SonarCloud Scanning
        run: |
          bash xccov-to-sonarqube-generic.sh result.xcresult > sonarqube-generic-coverage.xml

          brew install sonar-scanner

          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths="sonarqube-generic-coverage.xml" \
            -Dsonar.pullrequest.key=$pull_number \
            -Dsonar.pullrequest.branch=${{github.head_ref}} \
            -Dsonar.pullrequest.base=${{github.base_ref}}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check SonarCloud Results
        uses: sonarsource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496 # pin@v1.1.0
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}